import type {Gen} from '@feltjs/gro/gen/gen.js';
import {to_root_path} from '@feltjs/gro/util/paths.js';
import {load_package_json} from '@feltjs/gro/util/package_json.js';

export const gen: Gen = async ({origin_id}) => {
	const package_json = await load_package_json();

	const gen_info = `// generated by ${to_root_path(origin_id)}`;
	return `${gen_info}

// TODO probably change to import \`package.json\` directly without using codegen,
// for now this is convenient to avoid the complexity (exports, types, JSON import assertion)

import type {PackageJson} from '@feltjs/gro/util/package_json.js';

export const pkg = ${JSON.stringify(package_json)} satisfies PackageJson;

${gen_info}
`;
};
